# Generated by Django 3.2.18 on 2023-04-10 05:54

# Create all the new per endpoint permissions

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RconUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
            ],
            options={
                "permissions": (
                    (
                        "can_add_admin_roles",
                        "Can add HLL game server admin roles to players",
                    ),
                    ("can_add_map_to_rotation", "Can add a map to the rotation"),
                    ("can_add_maps_to_rotation", "Can add maps to the rotation"),
                    (
                        "can_add_player_comments",
                        "Can add comments to a players profile",
                    ),
                    ("can_add_vip", "Can add VIP status to players"),
                    ("can_ban_profanities", "Can ban profanities (censored game chat)"),
                    ("can_blacklist_players", "Can add players to the blacklist"),
                    (
                        "can_change_auto_broadcast_config",
                        "Can change the automated broadcast settings",
                    ),
                    ("can_change_auto_settings", "Can change auto settings"),
                    (
                        "can_change_autobalance_enabled",
                        "Can enable/disable autobalance",
                    ),
                    (
                        "can_change_autobalance_threshold",
                        "Can change the autobalance threshold",
                    ),
                    (
                        "can_change_broadcast_message",
                        "Can change the broadcast message",
                    ),
                    (
                        "can_change_camera_config",
                        "Can change camera notification settings",
                    ),
                    ("can_change_current_map", "Can change the current map"),
                    (
                        "can_change_discord_webhooks",
                        "Can change configured webhooks on the settings page",
                    ),
                    (
                        "can_change_idle_autokick_time",
                        "Can change the idle autokick time",
                    ),
                    (
                        "can_change_max_ping_autokick",
                        "Can change the max ping autokick",
                    ),
                    (
                        "can_change_profanities",
                        "Can add/remove profanities (censored game chat)",
                    ),
                    ("can_change_queue_length", "Can change the server queue size"),
                    ("can_change_real_vip_config", "Can change the real VIP settings"),
                    ("can_change_server_name", "Can change the server name"),
                    (
                        "can_change_shared_standard_messages",
                        "Can change the shared standard messages",
                    ),
                    (
                        "can_change_team_switch_cooldown",
                        "Can change the team switch cooldown",
                    ),
                    (
                        "can_change_vip_slots",
                        "Can change the number of reserved VIP slots",
                    ),
                    (
                        "can_change_votekick_autotoggle_config",
                        "Can change votekick settings",
                    ),
                    ("can_change_votekick_enabled", "Can enable/disable vote kicks"),
                    (
                        "can_change_votekick_threshold",
                        "Can change vote kick thresholds",
                    ),
                    ("can_change_votemap_config", "Can change the votemap settings"),
                    (
                        "can_change_welcome_message",
                        "Can change the welcome (rules) message",
                    ),
                    ("can_clear_crcon_cache", "Can clear the CRCON Redis cache"),
                    ("can_download_vip_list", "Can download the VIP list"),
                    ("can_flag_player", "Can add flags to players"),
                    ("can_kick_players", "Can kick players"),
                    ("can_message_players", "Can message players"),
                    ("can_perma_ban_players", "Can permanently ban players"),
                    ("can_punish_players", "Can punish players"),
                    (
                        "can_remove_admin_roles",
                        "Can remove HLL game server admin roles from players",
                    ),
                    ("can_remove_all_vips", "Can remove all VIPs"),
                    (
                        "can_remove_map_from_rotation",
                        "Can remove a map from the rotation",
                    ),
                    (
                        "can_remove_maps_from_rotation",
                        "Can remove maps from the rotation",
                    ),
                    ("can_remove_perma_bans", "Can remove permanent bans from players"),
                    ("can_remove_temp_bans", "Can remove temporary bans from players"),
                    ("can_remove_vip", "Can remove VIP status from players"),
                    ("can_reset_votekick_threshold", "Can reset votekick thresholds"),
                    ("can_reset_votemap_state", "Can reset votemap selection & votes"),
                    (
                        "can_run_raw_commands",
                        "Can send raw commands to the HLL game server",
                    ),
                    (
                        "can_switch_players_immediately",
                        "Can immediately switch players",
                    ),
                    ("can_switch_players_on_death", "Can switch players on death"),
                    ("can_temp_ban_players", "Can temporarily ban players"),
                    (
                        "can_toggle_services",
                        "Can enable/disable services (automod, etc)",
                    ),
                    (
                        "can_unban_profanities",
                        "Can unban profanities (censored game chat)",
                    ),
                    (
                        "can_unblacklist_players",
                        "Can remove players from the blacklist",
                    ),
                    ("can_unflag_player", "Can remove flags from players"),
                    ("can_remove_player_watch", "Can remove a watch from players"),
                    ("can_upload_vip_list", "Can upload a VIP list"),
                    ("can_view_admin_groups", "Can view available admin roles"),
                    (
                        "can_view_admin_ids",
                        "Can view the name/steam IDs/role of everyone with a HLL games erver admin role",
                    ),
                    (
                        "can_view_admins",
                        "Can view users with HLL game server admin roles",
                    ),
                    ("can_view_all_maps", "Can view all possible maps"),
                    (
                        "can_view_audit_logs_autocomplete",
                        "Can view the get_audit_logs_autocomplete endpoint",
                    ),
                    (
                        "can_view_audit_logs",
                        "Can view the can_view_audit_logs endpoint",
                    ),
                    (
                        "can_view_auto_broadcast_config",
                        "Can view the automated broadcast settings",
                    ),
                    ("can_view_auto_settings", "Can view auto settings"),
                    (
                        "can_view_autobalance_enabled",
                        "Can view if autobalance is enabled",
                    ),
                    (
                        "can_view_autobalance_threshold",
                        "Can view the autobalance threshold",
                    ),
                    ("can_view_available_services", "Can view serviecs (automod, etc)"),
                    (
                        "can_view_broadcast_message",
                        "Can view the current broadcast message",
                    ),
                    ("can_view_camera_config", "Can view camera notification settings"),
                    ("can_view_connection_info", "Can view CRCON's connection info"),
                    ("can_view_current_map", "Can view the currently playing map"),
                    (
                        "can_view_date_scoreboard",
                        "Can view the date_scoreboard endpoint",
                    ),
                    (
                        "can_view_detailed_player_info",
                        "Can view detailed player info (name, steam ID, loadout, squad, etc.)",
                    ),
                    (
                        "can_view_discord_webhooks",
                        "Can view configured webhooks on the settings page",
                    ),
                    (
                        "can_view_game_logs",
                        "Can view the get_logs endpoint (returns unparsed game logs)",
                    ),
                    ("can_view_gamestate", "Can view the current gamestate"),
                    (
                        "can_view_get_players",
                        "Can view get_players endpoint (name, steam ID, VIP status and sessions) for all connected players",
                    ),
                    (
                        "can_view_get_status",
                        "Can view the get_status endpoint (server name, current map, player count)",
                    ),
                    ("can_view_historical_logs", "Can view historical logs"),
                    ("can_view_idle_autokick_time", "Can view the idle autokick time"),
                    (
                        "can_view_ingame_admins",
                        "Can view admins connected to the game server",
                    ),
                    ("can_view_map_rotation", "Can view the current map rotation"),
                    ("can_view_max_ping_autokick", "Can view the max autokick ping"),
                    ("can_view_next_map", "Can view the next map in the rotation"),
                    ("can_view_online_admins", "Can view admins connected to CRCON"),
                    (
                        "can_view_online_console_admins",
                        "Can view the player name of all connected players with a HLL game server admin role",
                    ),
                    (
                        "can_view_other_crcon_servers",
                        "Can view other servers hosted in the same CRCON (forward to all servers)",
                    ),
                    ("can_view_perma_bans", "Can view permanently banned players"),
                    (
                        "can_view_player_bans",
                        "Can view all bans (temp/permanent) for a specific player",
                    ),
                    (
                        "can_view_player_comments",
                        "Can view comments added to a players profile",
                    ),
                    ("can_view_player_history", "Can view History > Players"),
                    (
                        "can_view_player_info",
                        "Can view the get_player_info endpoint (Name, steam ID, country and steam bans)",
                    ),
                    ("can_view_player_messages", "Can view messages sent to players"),
                    (
                        "can_view_player_profile",
                        "View the detailed player profile page",
                    ),
                    (
                        "can_view_player_slots",
                        "Can view the current/max players on the server",
                    ),
                    (
                        "can_view_playerids",
                        "Can view the get_playerids endpoint (name and steam IDs of connected players)",
                    ),
                    (
                        "can_view_players",
                        "Can view get_players_fast endpoint for all connected players ",
                    ),
                    (
                        "can_view_profanities",
                        "Can view profanities (censored game chat)",
                    ),
                    (
                        "can_view_queue_length",
                        "Can view the maximum size of the server queue",
                    ),
                    ("can_view_real_vip_config", "Can view the real VIP settings"),
                    ("can_view_recent_logs", "Can view recent logs (Live view)"),
                    (
                        "can_view_round_time_remaining",
                        "Can view the amount of time left in the round",
                    ),
                    ("can_view_scoreboard", "Can view the get_scoreboard endpoint"),
                    ("can_view_server_name", "Can view the server name"),
                    ("can_view_server_stats", "Can view the get_server_stats endpoint"),
                    (
                        "can_view_shared_standard_messages",
                        "Can view the shared standard messages",
                    ),
                    (
                        "can_view_structured_logs",
                        "Can view the get_structured_logs endpoint",
                    ),
                    (
                        "can_view_team_objective_scores",
                        "Can view the number of objectives held by each team",
                    ),
                    (
                        "can_view_team_switch_cooldown",
                        "Can view the team switch cooldown value",
                    ),
                    (
                        "can_view_detailed_players",
                        "Can view get_detailed_players endpoint",
                    ),
                    (
                        "can_view_team_view",
                        "Can view get_team_view endpoint (detailed player info by team for all connected players)",
                    ),
                    (
                        "can_view_teamkills_boards",
                        "Can view the get_teamkills_boards endpoint",
                    ),
                    ("can_view_temp_bans", "Can view temporary banned players"),
                    ("can_view_timed_logs", "Can view the get_timed_logs endpoint"),
                    ("can_view_vip_count", "Can view the number of connected VIPs"),
                    (
                        "can_view_vip_ids",
                        "Can view all players with VIP and their expiration timestamps",
                    ),
                    ("can_view_vip_slots", "Can view the number of reserved VIP slots"),
                    (
                        "can_view_votekick_autotoggle_config",
                        "Can view votekick settings",
                    ),
                    ("can_view_votekick_enabled", "Can view if vote kick is enabled"),
                    (
                        "can_view_votekick_threshold",
                        "Can view the vote kick thresholds",
                    ),
                    ("can_view_votemap_config", "Can view the votemap settings"),
                    (
                        "can_view_votemap_status",
                        "Can view the current votemap status (votes, results, etc)",
                    ),
                    ("can_view_welcome_message", "Can view the server welcome message"),
                    ("can_add_player_watch", "Can add a watch to players"),
                    (
                        "can_view_current_map_sequence",
                        "Can view the current map shuffle sequence",
                    ),
                    (
                        "can_view_map_shuffle_enabled",
                        "Can view if map shuffle is enabled",
                    ),
                    (
                        "can_change_map_shuffle_enabled",
                        "Can enable/disable map shuffle",
                    ),
                    ("can_view_map_whitelist", "Can view the votemap whitelist"),
                    (
                        "can_add_map_to_whitelist",
                        "Can add a map to the votemap whitelist",
                    ),
                    (
                        "can_add_maps_to_whitelist",
                        "Can add multiple maps to the votemap whitelist",
                    ),
                    (
                        "can_remove_map_from_whitelist",
                        "Can remove a map from the votemap whitelist",
                    ),
                    (
                        "can_remove_maps_from_whitelist",
                        "Can remove multiple maps from the votemap whitelist",
                    ),
                    ("can_reset_map_whitelist", "Can reset the votemap whitelist"),
                    ("can_set_map_whitelist", "Can set the votemap whitelist"),
                ),
                "default_permissions": (),
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
