# Generated by Django 3.2.18 on 2023-04-10 05:56

# This is a data migration to remove the default permissions created
# by Django because we are using subclasses for RconUser and SteamPlayer
# which are not used anywhere and will only confuse end users

from django.db import migrations

APP_LABEL = "api"


def delete_default_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    Permission = apps.get_model("auth.Permission")
    RconUser = apps.get_model("api..RconUser")
    SteamUser = apps.get_model("api.SteamPlayer")

    rcon_user_permissions_to_delete = (
        "add_rconuser",
        "change_rconuser",
        "delete_rconuser",
        "view_rconuser",
    )
    steam_player_permissions_to_delete = (
        "add_steamplayer",
        "change_steamplayer",
        "delete_steamplayer",
        "view_steamplayer",
    )

    content_type = ContentType.objects.get_for_model(RconUser)
    Permission.objects.filter(
        content_type=content_type, codename__in=rcon_user_permissions_to_delete
    ).delete()

    content_type = ContentType.objects.get_for_model(SteamUser)
    Permission.objects.filter(
        codename__in=steam_player_permissions_to_delete
    ).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_create_default_groups"),
    ]

    operations = [migrations.RunPython(delete_default_permissions)]
