ARG buildImage=node:20-bookworm-slim

FROM --platform=$BUILDPLATFORM $buildImage AS adminbuild

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
    apt-get update && \
    apt-get install -y --no-install-recommends git

WORKDIR /code

ENV REACT_APP_API_URL=/api/

RUN --mount=type=bind,source=rcongui/package.json,target=package.json,ro \
    --mount=type=bind,source=rcongui/package-lock.json,target=package-lock.json,ro \
    --mount=type=cache,target=/root/.npm \
    npm ci

COPY rcongui/ .

RUN --mount=type=cache,target=/root/.npm \
    npx update-browserslist-db@latest

COPY assets/shared/ /code/public/

RUN npm run build

RUN --mount=type=bind,source=.git,target=/tmp/git,ro \
    git --git-dir=/tmp/git describe --tags > /code/tag_version

FROM --platform=$BUILDPLATFORM $buildImage AS publicbuild

WORKDIR /code_public

RUN --mount=type=bind,source=rcongui_public/package.json,target=package.json,ro \
    --mount=type=bind,source=rcongui_public/package-lock.json,target=package-lock.json,ro \
    --mount=type=cache,target=/root/.npm \
    npm ci

COPY rcongui_public/ .
COPY assets/shared/ /code_public/public/

RUN npm run build

FROM nginx:mainline-alpine

RUN apk add --no-cache openssl

COPY --from=publicbuild /code_public/dist /var/www_public/
COPY --from=adminbuild /code/dist /var/www/
COPY --from=adminbuild /code/tag_version /code/tag_version

COPY assets/hll /code/assets/hll/
COPY assets/hllv /code/assets/hllv/
COPY --chmod=755 rcongui/entrypoint.sh /code/entrypoint.sh

VOLUME ["/static", "/certs", "/config"]

ENTRYPOINT [ "/code/entrypoint.sh" ]
