FROM arm64v8/node:15-stretch as build

WORKDIR /code

RUN mkdir /pw

COPY rcongui/package.json package.json
COPY rcongui/package-lock.json package-lock.json

RUN npm ci

ENV REACT_APP_API_URL /api/

COPY rcongui/src/ src/
COPY rcongui/public/ public/

COPY .git/ .git/
# Normal build
RUN npm run build

RUN mv /code/build /www
# Public build
ENV REACT_APP_PUBLIC_BUILD on
RUN npm run build
RUN mv /code/build /www_public

FROM arm64v8/nginx:mainline-alpine

COPY rcongui/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www

RUN mkdir /var/www_public/
COPY --from=build /www_public /var/www_public/
COPY --from=build /www /var/www/

VOLUME /certs
COPY rcongui/entrypoint.sh /code/entrypoint.sh
RUN chmod +x /code/entrypoint.sh

ENTRYPOINT [ "/code/entrypoint.sh" ]
