# Use official Go image as base
FROM golang:1.24 AS builder

WORKDIR /app

RUN apt update && apt install -y git
COPY .git/ .git/
RUN git describe --tags > /app/tag_version && rm -rf .git

COPY ./webhook_service .
RUN go mod vendor
RUN CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' -o webhook-service main.go
RUN chmod +x webhook-service

# Final stage
FROM scratch

WORKDIR /app

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/webhook-service .
COPY --from=builder /app/tag_version .


ENTRYPOINT ["/app/webhook-service"]