FROM arm64v8/python:3.8.12-bullseye

WORKDIR /code
RUN apt-get update -y && apt-get install -y cron logrotate cargo
COPY requirements.txt .
RUN pip install -U pip
RUN pip install -r requirements.txt
RUN pip install gunicorn
RUN pip install gunicorn[eventlet]
RUN pip install supervisor
COPY . .
ENV FLASK_APP rcon.connection
ENV PYTHONPATH /code/
RUN chmod +x entrypoint.sh
RUN chmod +x manage.py

ENTRYPOINT [ "/code/entrypoint.sh" ]
