FROM arm32v7/node:15-stretch as build

WORKDIR /code

RUN mkdir /pw

COPY rcongui/package.json package.json
COPY rcongui/package-lock.json package-lock.json

RUN npm ci

ENV REACT_APP_API_URL /api/

COPY rcongui/ .

COPY .git/ .git/
RUN git describe --tags > /code/tag_version
# Normal build
RUN npm run build

RUN mv /code/dist /www/
# Public build
ENV REACT_APP_PUBLIC_BUILD true
RUN npm run build
RUN mv /code/dist /www_public/

FROM arm32v7/nginx:mainlaine-alpine

RUN apk add openssl
COPY rcongui/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www

RUN mkdir /var/www_public/
COPY --from=build /www_public /var/www_public/
COPY --from=build /www /var/www/
COPY --from=build /code/tag_version /code/tag_version

VOLUME /certs
COPY rcongui/entrypoint.sh /code/entrypoint.sh
RUN chmod +x /code/entrypoint.sh

ENTRYPOINT [ "/code/entrypoint.sh" ]
