"""Add index to datetime

Revision ID: 0121ad1ee475
Revises: 11a37fe6d49c
Create Date: 2022-01-22 20:15:22.829537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0121ad1ee475'
down_revision = '11a37fe6d49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_server_counts_datapoint_time'), 'server_counts', ['datapoint_time'], unique=True)
    op.drop_constraint('server_counts_datapoint_time_key', 'server_counts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('server_counts_datapoint_time_key', 'server_counts', ['datapoint_time'])
    op.drop_index(op.f('ix_server_counts_datapoint_time'), table_name='server_counts')
    # ### end Alembic commands ###
