"""map stats

Revision ID: 0184d8fc0100
Revises: c0f61805ae28
Create Date: 2021-04-11 13:25:34.188212

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0184d8fc0100"
down_revision = "c0f61805ae28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creation_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=True),
        sa.Column("server_number", sa.Integer(), nullable=True),
        sa.Column("map_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "start", "end", "server_number", "map_name", name="unique_map"
        ),
    )
    op.create_index(op.f("ix_map_history_end"), "map_history", ["end"], unique=False)
    op.create_index(
        op.f("ix_map_history_map_name"), "map_history", ["map_name"], unique=False
    )
    op.create_index(
        op.f("ix_map_history_server_number"),
        "map_history",
        ["server_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_map_history_start"), "map_history", ["start"], unique=False
    )
    op.create_table(
        "player_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playersteamid_id", sa.Integer(), nullable=False),
        sa.Column("map_id", sa.Integer(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=True),
        sa.Column("kills_streak", sa.Integer(), nullable=True),
        sa.Column("death", sa.Integer(), nullable=True),
        sa.Column("deaths_without_kill_streak", sa.Integer(), nullable=True),
        sa.Column("teamkills", sa.Integer(), nullable=True),
        sa.Column("teamkills_streak", sa.Integer(), nullable=True),
        sa.Column("deaths_by_tk", sa.Integer(), nullable=True),
        sa.Column("deaths_by_tk_streak", sa.Integer(), nullable=True),
        sa.Column("nb_vote_started", sa.Integer(), nullable=True),
        sa.Column("nb_voted_yes", sa.Integer(), nullable=True),
        sa.Column("nb_voted_no", sa.Integer(), nullable=True),
        sa.Column("time_seconds", sa.Integer(), nullable=True),
        sa.Column("kills_per_minute", sa.Float(), nullable=True),
        sa.Column("deaths_per_minute", sa.Float(), nullable=True),
        sa.Column("kill_death_ratio", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["map_id"],
            ["map_history.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playersteamid_id"],
            ["steam_id_64.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playersteamid_id", "map_id", name="unique_map_player"),
    )
    op.create_index(
        op.f("ix_player_stats_map_id"), "player_stats", ["map_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_stats_playersteamid_id"),
        "player_stats",
        ["playersteamid_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_stats_playersteamid_id"), table_name="player_stats")
    op.drop_index(op.f("ix_player_stats_map_id"), table_name="player_stats")
    op.drop_table("player_stats")
    op.drop_index(op.f("ix_map_history_start"), table_name="map_history")
    op.drop_index(op.f("ix_map_history_server_number"), table_name="map_history")
    op.drop_index(op.f("ix_map_history_map_name"), table_name="map_history")
    op.drop_index(op.f("ix_map_history_end"), table_name="map_history")
    op.drop_table("map_history")
    # ### end Alembic commands ###
