"""stats

Revision ID: 04e1e8d9f37b
Revises: 028dee0924c2
Create Date: 2023-05-07 14:27:11.794188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04e1e8d9f37b'
down_revision = '028dee0924c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_lines', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('player_stats', sa.Column('combat', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('offense', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('defense', sa.Integer(), nullable=True))
    op.add_column('player_stats', sa.Column('support', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'support')
    op.drop_column('player_stats', 'defense')
    op.drop_column('player_stats', 'offense')
    op.drop_column('player_stats', 'combat')
    op.drop_column('log_lines', 'stats')
    # ### end Alembic commands ###
