"""Add author modified timestamp and session count to watchlist

Revision ID: 22e3790f2095
Revises: 99643dfdb5c3
Create Date: 2023-04-28 22:09:29.582135

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision = "22e3790f2095"
down_revision = "99643dfdb5c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_watchlist",
        sa.Column("modified", sa.DateTime(), nullable=True, server_default=func.now()),
    )
    op.add_column("player_watchlist", sa.Column("by", sa.String(), nullable=True))
    op.add_column(
        "player_watchlist",
        sa.Column("count", sa.Integer(), nullable=True, server_default="0"),
    )
    op.drop_column("player_watchlist", "comment")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_watchlist", "count")
    op.drop_column("player_watchlist", "by")
    op.drop_column("player_watchlist", "modified")
    op.add_column("player_watchlist", sa.Column("comment", sa.String(), nullable=True))
    # ### end Alembic commands ###
