"""empty message

Revision ID: 4a951ab7b8c6
Revises: 573029c13b1a
Create Date: 2021-02-02 20:30:15.727504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a951ab7b8c6'
down_revision = '573029c13b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
