"""empty message

Revision ID: 5bad2e454e04
Revises: 
Create Date: 2020-12-27 03:55:31.701433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bad2e454e04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_player_flags_flag'), 'player_flags', ['flag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_flags_flag'), table_name='player_flags')
    # ### end Alembic commands ###
