"""empty message

Revision ID: 5bad2e454e04
Revises: 
Create Date: 2020-12-27 03:55:31.701433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bad2e454e04'
down_revision = None
branch_labels = None
depends_on = None


def index_exists(name):
    connection = op.get_bind()
    result = connection.execute(
        "SELECT exists(SELECT 1 from pg_indexes where indexname = '{}') as ix_exists;"
            .format(name)
    ).first()
    return result.ix_exists

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not index_exists('ix_player_flags_flag'):
        op.create_index(op.f('ix_player_flags_flag'), 'player_flags', ['flag'], unique=False)
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_flags_flag'), table_name='player_flags')
    # ### end Alembic commands ###
