"""Add EOS ID column

Revision ID: 89a3502370a0
Revises: 0ac19ea4739e
Create Date: 2025-11-20 12:57:44.985471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89a3502370a0'
down_revision = '0ac19ea4739e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_soldier', sa.Column('eos_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_soldier', 'eos_id')
    # ### end Alembic commands ###
