"""empty message

Revision ID: 9124d6f7f696
Revises: c8bd6f43e802
Create Date: 2021-02-03 20:55:00.204106

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9124d6f7f696"
down_revision = "c8bd6f43e802"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("steam_info", sa.Column("country", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_steam_info_country"), "steam_info", ["country"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_steam_info_country"), table_name="steam_info")
    op.drop_column("steam_info", "country")
    # ### end Alembic commands ###
