"""empty message

Revision ID: c0f61805ae28
Revises: 9124d6f7f696
Create Date: 2021-03-07 08:02:16.684575

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c0f61805ae28'
down_revision = '9124d6f7f696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_sessions', sa.Column('server_name', sa.String(), nullable=True))
    op.add_column('player_sessions', sa.Column('server_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_sessions', 'server_number')
    op.drop_column('player_sessions', 'server_name')
    # ### end Alembic commands ###
