"""empty message

Revision ID: c8bd6f43e802
Revises: 4a951ab7b8c6
Create Date: 2021-02-03 19:41:07.279595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8bd6f43e802'
down_revision = '4a951ab7b8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playersteamid_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bans', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['playersteamid_id'], ['steam_id_64.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steam_info_playersteamid_id'), 'steam_info', ['playersteamid_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steam_info_playersteamid_id'), table_name='steam_info')
    op.drop_table('steam_info')
    # ### end Alembic commands ###
