"""added_comment

Revision ID: c9c06cc80fab
Revises: 0184d8fc0100
Create Date: 2021-05-15 13:43:53.003046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c06cc80fab'
down_revision = '0184d8fc0100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('playersteamid_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['playersteamid_id'], ['steam_id_64.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_player_comments_playersteamid_id'), 'player_comments', ['playersteamid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_comments_playersteamid_id'), table_name='player_comments')
    op.drop_table('player_comments')
    # ### end Alembic commands ###
