"""added_comment

Revision ID: dd31e8743d7e
Revises: d6da533e38e1
Create Date: 2021-05-15 15:30:27.579015

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd31e8743d7e'
down_revision = 'd6da533e38e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('playersteamid_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['playersteamid_id'], ['steam_id_64.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_player_comments_playersteamid_id'), 'player_comments', ['playersteamid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_comments_playersteamid_id'), table_name='player_comments')
    op.drop_table('player_comments')
    # ### end Alembic commands ###
