"""Add EOS ID

Revision ID: ded315ab4231
Revises: f80b6dc2833a
Create Date: 2025-11-17 13:27:58.013613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ded315ab4231'
down_revision = 'f80b6dc2833a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_id_64', sa.Column('eos_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_steam_id_64_eos_id'), 'steam_id_64', ['eos_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steam_id_64_eos_id'), table_name='steam_id_64')
    op.drop_column('steam_id_64', 'eos_id')
    # ### end Alembic commands ###
