"""fix deaths key in model to be consistent with the rest

Revision ID: ec5fc1135ddb
Revises: d50c73435c9c
Create Date: 2021-05-06 01:56:53.782695

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec5fc1135ddb"
down_revision = "d50c73435c9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("player_stats", "death", new_column_name="deaths")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("player_stats", "deaths", new_column_name="death")
    # ### end Alembic commands ###
