"""game_layout on Map

Revision ID: f80b6dc2833a
Revises: 1e8fd0c19cb0
Create Date: 2025-02-25 18:49:34.893468

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f80b6dc2833a'
down_revision = '1e8fd0c19cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_history', sa.Column('game_layout', sa.JSON, nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_history', 'game_layout')
    # ### end Alembic commands ###
