# Use official Go image as base
FROM golang:1.24 AS builder
WORKDIR /app

COPY . .
RUN go mod vendor
RUN go build -o webhook-service *.go

# Final stage
FROM golang:1.24
WORKDIR /app

# Copy the built binary from builder
COPY --from=builder /app/webhook-service .

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]