#!/usr/bin/env sh

export REACT_APP_VERSION=$(cat /code/tag_version)

if [ ! -f "/certs/cert.crt" ] || [ ! -f "/certs/key.key" ]; then
    echo "No certificates found. Generating self signed"
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /certs/key.key -out /certs/cert.crt -subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=$RCONWEB_EXTERNAL_ADDRESS" 
fi

# Build /etc/nginx/realip.conf (included by nginx.conf) from the RCONWEB_TRUSTED_PROXIES
# and RCONWEB_REAL_IP_HEADER .env values. This regenerates on every container start so
# changes to those .env values take effect on a simple restart.
#
# RCONWEB_REAL_IP_HEADER: name of the header a reverse proxy / load balancer / Cloudflare
#   Tunnel sets with the real client IP, e.g. X-Forwarded-For or CF-Connecting-IP.
#   Defaults to X-Forwarded-For.
# RCONWEB_TRUSTED_PROXIES: comma and/or space separated list of IPs/CIDRs allowed to set
#   that header (e.g. your reverse proxy's IP, or Cloudflare's ranges). If left empty,
#   nginx never trusts the header, and $remote_addr (and therefore X-Real-IP) is always
#   the address of whoever connects to it directly.
REAL_IP_HEADER="${RCONWEB_REAL_IP_HEADER:-X-Forwarded-For}"
REALIP_CONF=/etc/nginx/realip.conf

{
    echo "# Generated by entrypoint.sh from RCONWEB_TRUSTED_PROXIES / RCONWEB_REAL_IP_HEADER."
    echo "# Do not edit directly, this file is overwritten on every container start."
    echo "real_ip_header ${REAL_IP_HEADER};"
    echo "real_ip_recursive on;"

    OLD_IFS=$IFS
    IFS=', '
    for proxy in $RCONWEB_TRUSTED_PROXIES; do
        if [ -n "$proxy" ]; then
            echo "set_real_ip_from ${proxy};"
        fi
    done
    IFS=$OLD_IFS
} > "$REALIP_CONF"

if [ -z "$RCONWEB_TRUSTED_PROXIES" ]; then
    echo "RCONWEB_TRUSTED_PROXIES is not set, X-Real-IP will always be the direct connecting client's address"
else
    echo "Trusting ${REAL_IP_HEADER} from: ${RCONWEB_TRUSTED_PROXIES}"
fi

nginx -t && nginx -g "daemon off;"
